ci: neovim nightly name was changed
see https://github.com/neovim/neovim/pull/32194

also fix new prettier failure:

    > prettier --check . && eslint --format=unix .
    Checking formatting...
    [warn] nvim-macos-x86_64/share/nvim/runtime/pack/dist/opt/netrw/README.md
    [warn] Code style issues found in the above file. Run Prettier with --write to fix.
    Error: Process completed with exit code 1.