ci: skip lint on old node.js
Problem:

    > lint
    > eslint packages/*/src/**/*.ts packages/*/src/*.ts
    Oops! Something went wrong! :(
    ESLint: 8.56.0
    /Users/runner/work/node-client/node-client/node_modules/@typescript-eslint/scope-manager/dist/referencer/ClassVisitor.js:123
            withMethodDecorators ||=
                                 ^^^
    SyntaxError: Unexpected token '||='
        at wrapSafe (internal/modules/cjs/loader.js:1029:16)

Solution:
Don't run lint on older nodejs. Dev deps may require latest stuff.