[RFC] debug: spawn child process with --inspect-brk (#95)
Fix #46 

I included style changes because of the precommit check with husky.
Running node with `--inspect-brk` silences the following error whether I spawn a new host or not:

```
net.js:704
    throw new TypeError(
    ^

TypeError: Invalid data, chunk must be a string or buffer, not object
    at WriteStream.Socket.write (net.js:704:11)
    at Transport.parseMessage (/home/janlazo/repo/git/node-client/lib/utils/transport.js:105:31)
    at DecodeStream.Transport.decodeStream.on (/home/janlazo/repo/git/node-client/lib/utils/transport.js:37:18)
    at emitOne (events.js:116:13)
    at DecodeStream.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at DecodeStream.Readable.push (_stream_readable.js:208:10)
    at DecodeStream.Transform.push (_stream_transform.js:147:32)
    at DecodeBuffer.DecodeStream.decoder.push (/home/janlazo/repo/git/node-client/node_modules/msgpack-lite/lib/decode-stream.js:24:12)
```