fix(build): "Cannot find name 'expect'"
ref https://github.com/neovim/node-client/issues/352

Before:

    src/api/Buffer.test.ts:102:9 - error TS2304: Cannot find name 'expect'.
    ...
    src/api/Buffer.test.ts:106:5 - error TS2593: Cannot find name 'it'.
    Do you need to install type definitions for a test runner? Try `npm
    i --save-dev @types/jest` or `npm i --save-dev @types/mocha` and
    then add 'jest' or 'mocha' to the types field in your tsconfig.
    ...
    Found 616 errors in 8 files.

After:

    Found 138 errors in 6 files.