build: skipLibCheck
Problem:
build is checking declaration files in node_modules, which causes slower
compilation and isn't actionable:

    ../../node_modules/@types/node/globals.d.ts:72:13 - error TS2403:
    Subsequent variable declarations must have the same type.

Solution:
Set "skipLibCheck": true.